//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freientity.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbaluno
    {
        public int idaluno { get; set; }
        public int idturma { get; set; }
        public int nrchamada { get; set; }
        public string nmaluno { get; set; }
        public string dsbairro { get; set; }
        public string dsmunicipio { get; set; }
        public System.DateTime dtnascimento { get; set; }
    }
}
