//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freientity.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmedia
    {
        public int idmedia { get; set; }
        public string dsbimestre { get; set; }
        public decimal vlnota1 { get; set; }
        public decimal vlnota2 { get; set; }
        public decimal vlnota3 { get; set; }
        public decimal vlmedia { get; set; }
        public int idaluno { get; set; }
    }
}
