//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freientity.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbturma
    {
        public int idturma { get; set; }
        public string nmturma { get; set; }
        public string nmcurso { get; set; }
        public int qtmaxalunos { get; set; }
    }
}
