//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freientity.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbturma
    {
        public int idturma { get; set; }
        public string nmturma { get; set; }
        public string nmcurso { get; set; }
        public int qtmaxalunos { get; set; }
    }
}
