//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freitrabalho2._0.database.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class freitrabalhoEntities : DbContext
    {
        public freitrabalhoEntities()
            : base("name=freitrabalhoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblogin> tblogin { get; set; }
        public virtual DbSet<tbpergunta> tbpergunta { get; set; }
        public virtual DbSet<tbpontuacao> tbpontuacao { get; set; }
        public virtual DbSet<tbusuario> tbusuario { get; set; }
    }
}
