//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freitrabalho2._0.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblogin
    {
        public int idlogin { get; set; }
        public string senha { get; set; }
        public string nick { get; set; }
        public Nullable<int> idusuario { get; set; }
    }
}
