//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freitrabalho2._0.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbpergunta
    {
        public int idpergunta { get; set; }
        public string enunciado { get; set; }
        public string palternativa { get; set; }
        public string salternativa { get; set; }
        public string talternativa { get; set; }
        public string qalternativa { get; set; }
        public string resposta { get; set; }
        public string uf { get; set; }
    }
}
