//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freientity2._0.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbaluno
    {
        public int idaluno { get; set; }
        public int idturma { get; set; }
        public int nrchamada { get; set; }
        public string nmaluno { get; set; }
        public string dsbairro { get; set; }
        public string dsmunicipio { get; set; }
        public System.DateTime dtnascimento { get; set; }
    }
}
