//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freitrabalho.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbpergunta
    {
        public int idpergunta { get; set; }
        public string enunciado { get; set; }
        public string palternativa { get; set; }
        public string salternativa { get; set; }
        public string talternativa { get; set; }
        public string qalternativa { get; set; }
        public string resposta { get; set; }
        public string uf { get; set; }
    }
}
