//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freitrabalho.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbpontuacao
    {
        public int idpontuacao { get; set; }
        public Nullable<int> pontuacao { get; set; }
        public string nick { get; set; }
        public Nullable<int> idusuario { get; set; }
    
        public virtual tbusuario tbusuario { get; set; }
    }
}
