//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freitrabalho.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbusuario
    {
        public tbusuario()
        {
            this.tblogin = new HashSet<tblogin>();
            this.tbpontuacao = new HashSet<tbpontuacao>();
        }
    
        public int idusuario { get; set; }
        public string nick { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public string cargo { get; set; }
    
        public virtual ICollection<tblogin> tblogin { get; set; }
        public virtual ICollection<tbpontuacao> tbpontuacao { get; set; }
    }
}
