//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freientities.database.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmedia
    {
        public int idmedia { get; set; }
        public string dsbimestre { get; set; }
        public decimal vlnota1 { get; set; }
        public decimal vlnota2 { get; set; }
        public decimal vlnota3 { get; set; }
        public decimal vlmedia { get; set; }
        public int idaluno { get; set; }
    }
}
